### ISSUE TITLE
TypeError: namedtuple() got an unexpected keyword argument 'defaults'

### ISSUE THREAD

**Issue by toughkrua** [JackSlateur/backurne#2]
Hello! I hope for you help.

Ubuntu 14.04
Installed python3.6 and required modules
python3.6 install.py build; python3.6 install.py install (no errors)
#backurne
Traceback (most recent call last):
  File "/usr/local/bin/backurne", line 11, in <module>
    load_entry_point('backurne==2.0.0', 'console_scripts', 'backurne')()
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2862, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2462, in load
    return self.resolve()
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2468, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/usr/local/lib/python3.6/dist-packages/backurne-2.0.0-py3.6.egg/backurne/backurne.py", line 23, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/usr/local/lib/python3.6/dist-packages/backurne-2.0.0-py3.6.egg/backurne/restore.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/usr/local/lib/python3.6/dist-packages/backurne-2.0.0-py3.6.egg/backurne/disk.py", line 15, in <module>
TypeError: namedtuple() got an unexpected keyword argument 'defaults'

**Comment by JackSlateur** [comment]
Hello
Python 3.7 is required

I just updated the readme etc to fix the requirement
